### ISSUE TITLE
[1.20.1/Version 1.0.0] Startup failed

### ISSUE THREAD

**Issue by lushangkan** [Thepigcat76/Tech-enhanced#1]
Mods list: https://pastebin.com/xpU2bZbE
System version: Windows 11
Jdk version: LibericaJDK-17
Minecraft version: 1.20.1
Mod version: 1.0.0
Techreborn version: 5.8.1
Fabric version: 0.14.21
Fabric API version: 0.184.0
Error logs: https://pastebin.com/a797g6Mi

Need more information, please reply

**Comment by Thepigcat76** [comment]
Eww mixins. Should be an easy fix tho

**Comment by Thepigcat76** [comment]
can you try this version? https://legacy.curseforge.com/minecraft/mc-mods/tech-enhanced/files/4602639

**Comment by lushangkan** [comment]
> can you try this version? https://legacy.curseforge.com/minecraft/mc-mods/tech-enhanced/files/4602639

New error: java.lang.NoClassDefFoundError: net/minecraft/item/Item$Settings
Error logs: https://pastebin.com/AEhph862

The previous error has disappeared

**Comment by Thepigcat76** [comment]
Was fixed in the latest version
