### ISSUE TITLE
Got a crash and I thought it would be better to give it to the mod creator

### ISSUE THREAD

**Issue by Noahfrechette** [Thepigcat76/Tech-enhanced#2]
[crash-2023-06-22_17.24.46-client.txt](https://github.com/Thepigcat76/Tech-enhanced/files/11840867/crash-2023-06-22_17.24.46-client.txt)
what I did to get it was add it and then when loading it it crashed

**Comment by Thepigcat76** [comment]
Someone has already reported that but thanks. I think is a problem with the depencies, will try to look into it

**Comment by Thepigcat76** [comment]
Has been fixed in the latest release
